[config]
general = "powersave"
powersave = [""]
balance = [""]
performance = [""]

[freqs]
general = [300000, 300000]
powersave = [300000, 300000]
balance = [300000, 300000]
performance = [300000, 300000]

[governors]
general = "walt"
powersave = "walt"
balance = "walt"
performance = "walt"